<?php
/**
 * @file
 * A module exemplifying Drupal coding practices and APIs.
 *
 * This module provides a block that lists all of the
 * installed modules. It illustrates coding standards,
 * practices, and API use Drupal 7.
 */

/**
 * Implements hook_help()
 */
function first_help($path, $arg){
  if ($path == "admin/help#first") {
    return t("A demonstration module.");
  }
}

/**
 * Implements hook_block_info()
 */
function first_block_info(){
  $blocks = array();

  $blocks["list_modules"] = array(
    "info" => t("A listing of all the enabled modules"),
    "cache" => DRUPAL_NO_CACHE
  );

  return $blocks;
}